"""make items spec nullable

Revision ID: c4db68a2c257
Revises: 481c2a16e72d
Create Date: 2026-07-07 17:12:44.351123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4db68a2c257'
down_revision: Union[str, Sequence[str], None] = '481c2a16e72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'spec',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('items', 'spec',
               existing_type=sa.TEXT(),
               nullable=False)
