"""add storage locations, items, receipts, stock, withdrawals

Revision ID: f9b110a57f38
Revises: 
Create Date: 2026-07-04 20:21:46.239779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9b110a57f38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('spec', sa.Text(), nullable=False),
    sa.Column('base_unit', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_storage_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('central', 'unit', 'project_site', name='storagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_storage_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_members',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('leader', 'employee', name='locationrole'), nullable=False),
    sa.ForeignKeyConstraint(['storage_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('storage_id', 'user_id')
    )
    op.create_table('po_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('po_id', sa.BigInteger(), nullable=True),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('item_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('location', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('received_by', sa.BigInteger(), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_levels',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'location_id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('movement_type', sa.Enum('receive', 'withdraw', 'transfer_in', 'transfer_out', 'return_to_supplier', 'dispose', 'adjust', name='movementtype'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_type', sa.Text(), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('po_item_id', sa.BigInteger(), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rejected_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('condition', sa.Enum('good', 'damaged_package_unopened', 'damaged', 'wrong_item', name='receiptcondition'), server_default='good', nullable=False),
    sa.Column('condition_note', sa.Text(), nullable=True),
    sa.Column('return_to_supplier', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['po_item_id'], ['po_items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_photos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('server_uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id', 'sha256_hash')
    )
    op.create_table('withdrawal_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('withdrawal_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['withdrawal_id'], ['withdrawals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('delivery_photos', 'sha256_hash',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=False)
    
    op.add_column('purchase_orders', sa.Column('project_id', sa.BigInteger(), nullable=True))
    
    op.drop_constraint(op.f('purchase_orders_material_request_id_fkey'), 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'projects', ['project_id'], ['id'])
    op.drop_column('purchase_orders', 'material_request_id')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('owner', 'buyer', 'onsite', 'factory', 'engineer', name='userrole'),
               type_=postgresql.ENUM('owner', 'buyer', 'onsite', 'factory', 'engineer', name='user_role'),
               existing_nullable=False)
    op.add_column('purchase_orders', sa.Column('material_request_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_orders_material_request_id_fkey'), 'purchase_orders', 'material_requests', ['material_request_id'], ['id'])
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.Enum('pending', 'delivered', 'cancelled', name='orderstatus'),
               type_=postgresql.ENUM('pending', 'delivered', 'cancelled', name='order_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::order_status"))
    op.drop_column('purchase_orders', 'project_id')
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('active', 'completed', 'on_hold', name='projectstatus'),
               type_=postgresql.ENUM('active', 'completed', 'on_hold', name='project_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::project_status"))
    op.alter_column('material_requests', 'urgency',
               existing_type=sa.Enum('low', 'medium', 'high', name='urgencylevel'),
               type_=postgresql.ENUM('low', 'medium', 'high', name='urgency_level'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::urgency_level"))
    op.alter_column('material_requests', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='requeststatus'),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='request_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::request_status"))
    op.alter_column('delivery_photos', 'sha256_hash',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.drop_table('withdrawal_lines')
    op.drop_table('receipt_photos')
    op.drop_table('receipt_lines')
    op.drop_table('withdrawals')
    op.drop_table('stock_movements')
    op.drop_table('stock_levels')
    op.drop_table('receipts')
    op.drop_table('po_items')
    op.drop_table('location_members')
    op.drop_table('storage_locations')
    op.drop_table('items')
    # ### end Alembic commands ###
